name: microsoft_graph_api
description: The microsoft_graph_api package is a robust and streamlined Flutter solution for Microsoft Graph API integration. It empowers developers to interact seamlessly with Microsoft 365 data resources like user information, calendars, mail, and Teams data. The package abstracts the complexities of authentication, API calls, and response handling, while providing customizable authentication flows. Ideal for crafting high-quality Flutter applications that can securely access Microsoft 365 data.
version: 0.0.3
repository: https://github.com/PlaxXOnline/microsoft_graph_api
issue_tracker: https://github.com/PlaxXOnline/microsoft_graph_api/issues

platforms:
  android:
  ios:
  windows:
  linux:
  macos:
  web:

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dio: ^5.2.1+1
  mockito: ^5.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5

flutter:
  assets:
    - assets/user-shadow.png
